package charity.viewUser;

import charity.UserController.DonationListController;
import com.sun.source.tree.DoWhileLoopTree;
import javax.swing.JFrame;

public class DonationListPanel extends javax.swing.JPanel {

    private int userId;
    private DonationListController controller = null;

    public DonationListPanel(JFrame parent, int userID) {
        initComponents();
        this.userId = userID;
        controller= new DonationListController(txtSearch, jrbtId, jrbtEvent, jrbtUser, jbtReset, jpnTable);
        controller.setDonationListTable();
        controller.setEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeSearch = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        gradientPanel2 = new charity.viewUser.GradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jrbtId = new javax.swing.JRadioButton();
        jrbtEvent = new javax.swing.JRadioButton();
        jrbtUser = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jbtReset = new javax.swing.JButton();
        jpnTable = new javax.swing.JPanel();

        setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Danh sách quyên góp");

        javax.swing.GroupLayout gradientPanel2Layout = new javax.swing.GroupLayout(gradientPanel2);
        gradientPanel2.setLayout(gradientPanel2Layout);
        gradientPanel2Layout.setHorizontalGroup(
            gradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addContainerGap(803, Short.MAX_VALUE))
        );
        gradientPanel2Layout.setVerticalGroup(
            gradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(149, 79));
        jPanel3.setLayout(null);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel3.add(txtSearch);
        txtSearch.setBounds(100, 10, 170, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tìm kiếm");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 10, 70, 30);

        jrbtId.setBackground(new java.awt.Color(255, 255, 255));
        typeSearch.add(jrbtId);
        jrbtId.setSelected(true);
        jrbtId.setText("Id");
        jPanel3.add(jrbtId);
        jrbtId.setBounds(300, 11, 50, 30);

        jrbtEvent.setBackground(new java.awt.Color(255, 255, 255));
        typeSearch.add(jrbtEvent);
        jrbtEvent.setText("Sự kiện");
        jPanel3.add(jrbtEvent);
        jrbtEvent.setBounds(350, 10, 70, 30);

        jrbtUser.setBackground(new java.awt.Color(255, 255, 255));
        typeSearch.add(jrbtUser);
        jrbtUser.setText("Người quyên góp");
        jPanel3.add(jrbtUser);
        jrbtUser.setBounds(420, 10, 130, 30);

        jButton1.setText("jButton1");
        jPanel3.add(jButton1);
        jButton1.setBounds(860, 10, 75, 23);

        jbtReset.setText("Làm mới");
        jPanel3.add(jbtReset);
        jbtReset.setBounds(945, 10, 80, 23);

        jpnTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnTableLayout = new javax.swing.GroupLayout(jpnTable);
        jpnTable.setLayout(jpnTableLayout);
        jpnTableLayout.setHorizontalGroup(
            jpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jpnTableLayout.setVerticalGroup(
            jpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jpnTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(gradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jpnTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        add(jPanel2);
        jPanel2.setBounds(0, 0, 1028, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private charity.viewUser.GradientPanel gradientPanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtReset;
    private javax.swing.JPanel jpnTable;
    private javax.swing.JRadioButton jrbtEvent;
    private javax.swing.JRadioButton jrbtId;
    private javax.swing.JRadioButton jrbtUser;
    private javax.swing.JTextField txtSearch;
    private javax.swing.ButtonGroup typeSearch;
    // End of variables declaration//GEN-END:variables
}
