package charity.viewUser;

import charity.UserController.MyDonationController;
import javax.swing.JFrame;

/**
 *
 * @author phaml
 */
public class MyDonationPanel extends javax.swing.JPanel {
    private int userId;
    private int accountId;
    MyDonationController controller =null;

    public MyDonationPanel(JFrame parent, int accountId,int userId) {
        initComponents();
        this.accountId= accountId;
        this.userId = userId;
        controller = new MyDonationController(userId,txtSearch, jrbtId, jrbtEvent, jtbtUser, jbtReset, jbtPrint, jpnTable);
        controller.setDonationListTable();
        controller.setEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        gradientPanel1 = new charity.viewUser.GradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jrbtId = new javax.swing.JRadioButton();
        jrbtEvent = new javax.swing.JRadioButton();
        jtbtUser = new javax.swing.JRadioButton();
        jbtReset = new javax.swing.JButton();
        jbtPrint = new javax.swing.JButton();
        jpnTable = new javax.swing.JPanel();

        setLayout(null);

        gradientPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lịch sử quyên góp");
        gradientPanel1.add(jLabel1);
        jLabel1.setBounds(25, 23, 155, 25);

        add(gradientPanel1);
        gradientPanel1.setBounds(0, 0, 1025, 70);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setText("Tìm kiếm");

        buttonGroup1.add(jrbtId);
        jrbtId.setSelected(true);
        jrbtId.setText("Id");

        buttonGroup1.add(jrbtEvent);
        jrbtEvent.setText("Sự kiện");

        buttonGroup1.add(jtbtUser);
        jtbtUser.setText("Người quyên góp");

        jbtReset.setText("Làm mới");

        jbtPrint.setText("Xuất danh sách");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbtId)
                .addGap(18, 18, 18)
                .addComponent(jrbtEvent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtbtUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                .addComponent(jbtPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtReset)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jrbtId)
                    .addComponent(jrbtEvent)
                    .addComponent(jtbtUser)
                    .addComponent(jbtReset)
                    .addComponent(jbtPrint))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 90, 1030, 40);

        javax.swing.GroupLayout jpnTableLayout = new javax.swing.GroupLayout(jpnTable);
        jpnTable.setLayout(jpnTableLayout);
        jpnTableLayout.setHorizontalGroup(
            jpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jpnTableLayout.setVerticalGroup(
            jpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        add(jpnTable);
        jpnTable.setBounds(40, 150, 950, 280);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private charity.viewUser.GradientPanel gradientPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtPrint;
    private javax.swing.JButton jbtReset;
    private javax.swing.JPanel jpnTable;
    private javax.swing.JRadioButton jrbtEvent;
    private javax.swing.JRadioButton jrbtId;
    private javax.swing.JRadioButton jtbtUser;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
